<meta name='viewport' content='width=device-width, initial-scale=1.0'>

<link rel="shortcut icon" href="asset/img/icon/favicon.ico" type="image/x-icon">

<!-- jQuery -->
<script src="http://code.jquery.com/jquery-latest.min.js"></script>

<!-- Image slider http://imageslidermaker.com/v2 -->
<script src="asset/lib/ism/js/ism-2.2.min.js"></script>


<!-- http://scottjehl.github.io/picturefill/ -->
<script>
    document.createElement("picture");
</script>
<script src="asset/lib/js/picturefill.min.js" async></script>

<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

<!-- My Custom Javascript and CSS -->
<script type="text/javascript" src="asset/js/script.js?v=6" async></script>
<link rel="stylesheet" href="asset/css/styles.css?v=11">
