<header>
    <div class="header-top">
       <img src="asset/img/header/logo_img.png" class="logo-img" alt="Travel Review Logo Image">
        <h1 class="logo-title">Travel</h1>
        <h1 class="logo-title">Wave</h1>
    </div>
    <div class="searchbox-desktop">
        <form>
            <input type="text" placeholder="Search..." required>
            <input type="button" class="search-btn" value="Search">
        </form>

    </div>

    <div id="cssmenu">
        <ul>
            <li><a href="#"><span><i class="fa fa-fw fa-bars"></i> Places</span></a>
                <ul>
                    <li><a href="/hawaii"><span>Hawaii</span></a></li>
                    <li><a href="/boracay"><span>Boracay</span></a></li>
                    <li><a href="/manila"><span>Manila</span></a></li>
                </ul>
            </li>
            <li><a href="#"><span><i class="fa fa-fw fa-paper-plane"></i> Travel Services</span></a></li>
            <li><a href="#"><span><i class="fa fa-fw fa-street-view"></i> About Us</span></a></li>
            <li><a href="#"><span><i class="fa fa-fw fa-phone"></i> Contact</span></a></li>
        </ul>
    </div>
</header>





