<header class="header-top">
    <img src="asset/img/header/logo_img.png" class="logo-img" alt="Travel Review Logo Image">
    <h1 class="logo-title">Travel Wave</h1>

    <nav id="cssmenu">
        <ul>
            <li><a href="#"><span><i class="fa fa-fw fa-bars"></i> Places</span></a>
                <ul>
                    <?php include("pages/places/01-parts/03-navigation_places.inc"); ?>
                </ul>
            </li>
            <li><a href="#"><span><i class="fa fa-fw fa-paper-plane"></i> Services</span></a></li>
            <li><a href="#"><span><i class="fa fa-fw fa-street-view"></i> About Us</span></a></li>
            <li><a href="#"><span><i class="fa fa-fw fa-phone"></i> Contact</span></a></li>
        </ul>
    </nav>


    <div class="searchbox-desktop">
        <form>
            <input type="text" placeholder="Search..." required>
            <input type="button" class="search-btn" value="Search">
        </form>
        <form class="search-bar" role="search">
            <input type="search" placeholder="Enter Search" />
            <button type="submit">
                <img src="https://raw.githubusercontent.com/thoughtbot/refills/master/source/images/search-icon-black.png" alt="Search Icon">
            </button>
        </form>
    </div>
</header>
<!--
<div class="social-media-desktop">
    <nav>
        <ul>
            <li><a target="_blank" href="https://www.facebook.com/funda.web.3"><img
                        src="asset/img/social-media/fb_icon.png" alt="Footer link to facebook page"></a></li>
            <li><a target="_blank" href="https://www.facebook.com/funda.web.3"><img
                        src="asset/img/social-media/twitter_icon.jpg" alt="Footer link to twitter page"></a>
            </li>
            <li><a target="_blank" href="https://www.facebook.com/funda.web.3"><img
                        src="asset/img/social-media/instagram_icon.png"
                        alt="Footer link to Instagram page"></a></li>
            <li><a target="_blank" href="https://www.facebook.com/funda.web.3"><img
                        src="asset/img/social-media/pinterest_icon.png"
                        alt="Footer link to Pinterest page"></a></li>
            <li><a target="_blank" href="https://www.facebook.com/funda.web.3"><img
                        src="asset/img/social-media/googleplus_icon.png" alt="Footer link to Google Plus page"></a>
            </li>
        </ul>
    </nav>
</div>
-->